name: Update dorm capacities

on:
  schedule:
    - cron: "25 * * * *"
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Fetch dorm data
        run: node check.js

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add dorms.json

          git commit -m "Update dorm capacities" || exit 0

          git push
